name: "Conventional PR title"

on:
  workflow_call:
    inputs:
      validateSingleCommit:
        description: 'Whether to validate single commit PR'
        required: false
        type: boolean
        default: true
    secrets:
      GH_TOKEN:
        required: true

jobs:
  verify_conventional_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          validateSingleCommit: ${{ inputs.validateSingleCommit }}
